name: ndb-site

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: npm install
        run: |
          npm ci
          npm run build

      # - name: npm test
      #   run: npm test
